### ISSUE TITLE
Failed In Reproducing Results In The Paper

### ISSUE THREAD

**Issue by HaixinShi** [YangHai-1218/SCFlow#1]
Dear Author,

Thank you very much for sharing the code to the community!

I tried to reproduce the YCBV results in your paper but failed. The first question came to my mind was "Can the provided pretrained [ycbv_mixpbr](https://drive.google.com/file/d/1SYfGKCHUFUIqKkVvJArHwl32kS3yTMes/view?usp=drive_link) reach around 0.82 AR of BOP metrics in YCBV dataset?" I can only reach around 0.79 AR. 

Thanks a lot in advance!

Best,
Haixin

**Comment by YangHai-1218** [comment]
Wo do four recurrent refinements to compare with other methods in Table 2

**Comment by A7eNg** [comment]
Dear HaixinShi,

Have you met KeyError Exceptions during the reproducing?

**Comment by zhangjy328** [comment]
@HaixinShi 
Dear HaixinShi,
I cannot get mmcv-full to be compatible. Have you encountered the same problem? If so, which version did you switch to? I am using Python 3.9, CUDA 11.3, and PyTorch 1.12.1.


ImportError: /root/miniconda3/envs/py3d/lib/python3.9/site-packages/mmcv/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l
