### ISSUE TITLE
Inquiry about the source of 'models_1024'

### ISSUE THREAD

**Issue by Turmir** [YangHai-1218/SCFlow#9]
Hello,

I hope this message finds you well. I am currently working on a project and have been using the train.py and rendering.py script provided in the repository. I have encountered a line of code where I need to set the directory for mesh data:

_mesh_dir = dataset_root + '/models_1024'

I am unsure about the purpose and meaning of 'models_1024'. Could you please provide some insight into what this directory is intended for and where I can obtain or generate the data it refers to?

I would greatly appreciate any guidance you could offer on this matter.

Thank you for your attention and support.

Best regards.

**Comment by YangHai-1218** [comment]
Hey, thanks for you interest. '1024' means that we downsample the texture map to 1024*1024 resolution for saving the memory usage.

**Comment by Turmir** [comment]
> Hey, thanks for you interest. '1024' means that we downsample the texture map to 1024*1024 resolution for saving the memory usage.

Thank you for your prompt response! I have downsampled the PNG images that store texture information, and it has indeed reduced the memory usage.
